#include "battery.h"
#include <fonts.h>
#include <zephyr/kernel.h>

/* 18x16 battery widget bitmaps (MSB-first, 3 bytes/row), generated by
 * sim/gen_battery_widget.py — shell outline + terminal, reference-style
 * piercing bolt, and the bolt's 1px halo ring. Do not hand-edit. */
#define BATT_W 18
#define BATT_H 16
#define BATT_STRIDE ((BATT_W + 7) / 8)

static const uint8_t batt_shell[BATT_H * BATT_STRIDE] = {
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xff, 0xff, 0x00, 0x80, 0x01, 0x00,
    0x80, 0x01, 0x00, 0x80, 0x01, 0x00, 0x80, 0x01, 0x80, 0x80, 0x01, 0x80,
    0x80, 0x01, 0x80, 0x80, 0x01, 0x80, 0x80, 0x01, 0x00, 0x80, 0x01, 0x00,
    0x80, 0x01, 0x00, 0xff, 0xff, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
};

static const uint8_t batt_bolt[BATT_H * BATT_STRIDE] = {
    0x00, 0x30, 0x00, 0x00, 0x60, 0x00, 0x00, 0x60, 0x00, 0x00, 0xc0, 0x00,
    0x00, 0xc0, 0x00, 0x01, 0x80, 0x00, 0x01, 0x80, 0x00, 0x07, 0xf0, 0x00,
    0x00, 0x60, 0x00, 0x00, 0xc0, 0x00, 0x00, 0xc0, 0x00, 0x01, 0x80, 0x00,
    0x01, 0x80, 0x00, 0x03, 0x00, 0x00, 0x06, 0x00, 0x00, 0x0c, 0x00, 0x00,
};

static const uint8_t batt_halo[BATT_H * BATT_STRIDE] = {
    0x00, 0x48, 0x00, 0x00, 0x90, 0x00, 0x00, 0x90, 0x00, 0x01, 0x20, 0x00,
    0x01, 0x20, 0x00, 0x02, 0x40, 0x00, 0x06, 0x70, 0x00, 0x08, 0x08, 0x00,
    0x07, 0x90, 0x00, 0x01, 0x20, 0x00, 0x01, 0x20, 0x00, 0x02, 0x40, 0x00,
    0x02, 0x40, 0x00, 0x04, 0x80, 0x00, 0x09, 0x00, 0x00, 0x12, 0x00, 0x00,
};

#if IS_ENABLED(CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_SMART_BATTERY)
LV_IMG_DECLARE(crystal_01);
LV_IMG_DECLARE(crystal_02);
LV_IMG_DECLARE(crystal_03);
LV_IMG_DECLARE(crystal_04);
LV_IMG_DECLARE(crystal_05);
LV_IMG_DECLARE(crystal_06);
LV_IMG_DECLARE(crystal_07);
LV_IMG_DECLARE(crystal_08);
LV_IMG_DECLARE(crystal_09);
LV_IMG_DECLARE(crystal_10);
LV_IMG_DECLARE(crystal_11);
LV_IMG_DECLARE(crystal_12);
LV_IMG_DECLARE(crystal_13);
LV_IMG_DECLARE(crystal_14);
LV_IMG_DECLARE(crystal_15);
LV_IMG_DECLARE(crystal_16);

#ifndef SET_ANIMATION_SMART_BATTERY_OFF
#define SET_ANIMATION_SMART_BATTERY_OFF &crystal_01
#endif

const lv_img_dsc_t *crystal_imgs_test[] = {
    &crystal_01, &crystal_02, &crystal_03, &crystal_04, &crystal_05, &crystal_06,
    &crystal_07, &crystal_08, &crystal_09, &crystal_10, &crystal_11, &crystal_12,
    &crystal_13, &crystal_14, &crystal_15, &crystal_16,
};

static lv_obj_t *art = NULL;
static lv_obj_t *art2 = NULL;

void animation_smart_battery_on(lv_obj_t *canvas) {
    if (art2) {
        lv_obj_del(art2);
        art2 = NULL;
    }
    art = lv_animimg_create(canvas);
    lv_obj_center(art);

    lv_animimg_set_src(art, (const void **)crystal_imgs_test, 16);
    lv_animimg_set_duration(art, CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_MS);
    lv_animimg_set_repeat_count(art, LV_ANIM_REPEAT_INFINITE);
    lv_animimg_start(art);
    lv_obj_align(art, LV_ALIGN_TOP_LEFT, CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_CUSTOM_X, CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_CUSTOM_Y);
}
void animation_smart_battery_off(lv_obj_t *canvas) {
    if (art) {
        lv_obj_del(art);
        art = NULL;
    }
    art2 = lv_img_create(canvas);
    lv_img_set_src(art2, SET_ANIMATION_SMART_BATTERY_OFF);
    lv_obj_align(art2, LV_ALIGN_TOP_LEFT, CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_CUSTOM_X, CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_CUSTOM_Y);
}
#endif

static void draw_level(lv_obj_t *canvas, const struct status_state *state) {
    lv_draw_label_dsc_t label_dsc;
    init_label_dsc(&label_dsc, LVGL_FOREGROUND, &pixel_operator_mono_12, LV_TEXT_ALIGN_CENTER);

    char text[10] = {};

    /* Upstream-style power display: hollow shell whose interior fills with
     * the charge level (empty = outline only, full = solid), percentage to
     * its right. While charging the reference-style bolt pierces the shell
     * top-to-bottom; its 1px halo ring is cleared first so the bolt stays
     * separated from shell and fill. */
    const int ox = CONFIG_NICE_OLED_WIDGET_BATTERY_CUSTOM_X + 2;
    const int oy = CONFIG_NICE_OLED_WIDGET_BATTERY_CUSTOM_Y + 2;
    const int fill_cols = (state->battery * 14 + 50) / 100; /* 14 interior cols */
    const lv_color_t ink = LVGL_FOREGROUND;
    const lv_color_t bg = LVGL_BACKGROUND;
    for (int y = 0; y < BATT_H; y++) {
        for (int x = 0; x < BATT_W; x++) {
            const uint8_t bit = 0x80 >> (x & 7);
            const int i = y * BATT_STRIDE + (x >> 3);
            bool v = (batt_shell[i] & bit) != 0;
            if (y >= 3 && y <= 12 && x >= 1 && x <= 14 && (x - 1) < fill_cols) {
                v = true;
            }
            if (state->charging) {
                if (batt_halo[i] & bit) {
                    v = false;
                }
                if (batt_bolt[i] & bit) {
                    v = true;
                }
            }
            lv_canvas_set_px(canvas, ox + x, oy + y, v ? ink : bg);
        }
    }
    /* Centred in the slot between the two icons: battery ink ends at x18, the
     * WiFi/USB box starts at x46, so the digits sit in x20..45. mono12 makes
     * the widest string "100%" 24px of advance, so the box must stay >= 24 or
     * LVGL would wrap it. */
    snprintf(text, sizeof(text), "%i%%", state->battery);
    lv_canvas_draw_text(canvas, CONFIG_NICE_OLED_WIDGET_BATTERY_CUSTOM_X + 20,
                        CONFIG_NICE_OLED_WIDGET_BATTERY_CUSTOM_Y + 5, 26, &label_dsc, text);
}

void draw_battery_status(lv_obj_t *canvas, const struct status_state *state) {
    /* Custom: "BAT" label removed; percentage moved to top row (see Kconfig defaults) */
    draw_level(canvas, state);
}

